version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    resource_class: medium

jobs:
  docker-build-and-push:
    executor: docker-executor
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true

      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use --name multiarch-builder
            docker buildx inspect --bootstrap

      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build and Push Multi-Arch Image
          command: |
            IMAGE_NAME=myusername/myimage
            TAG=latest

            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag $IMAGE_NAME:$TAG \
              --push .

workflows:
  version: 2
  build_and_push:
    jobs:
      - docker-build-and-push