version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    resource_class: medium

jobs:
  docker-build-and-push:
    executor: docker-executor
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use --name multiarch-builder
            docker buildx inspect --bootstrap

      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build and Push Multi-Arch Images for PG Versions
          command: |
            IMAGE_NAME=andriotisnikos1/pg-backup
            for VERSION in 15 14; do
              docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --build-arg POSTGRES_VERSION=$VERSION \
                --tag $IMAGE_NAME:pg-$VERSION \
                --push .
            done
            docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --tag $IMAGE_NAME \
                --push .

workflows:
  build_and_push:
    jobs:
      - docker-build-and-push:
          filters:
            branches:
              only: main